# https://dantehranian.wordpress.com/2015/03/25/how-should-i-get-application-configuration-into-my-docker-containers/
# Used 1 way due to API was already using config.json,
# TODO: REPLACE CONFIG WITH ENV VALUES. It is fast, safe, and it is the best practice.

version: '3.9'
services:
  web:
    container_name: activity_api
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .
    # tag an image to avoid unnecessary image rebuilding 
    image: activity_api:latest
    # map port
    ports:
      - "9332:9332"
    # Launch Redis first
    depends_on:
      - redis
    # I don't see any need in this lab to map volumes.
#    # map root dir to /activity_api, this allows to make changes to the project during the local development process (for possible future unit testing?)
#    volumes:
#      - .:/activity_api
  redis:
    image: "redis:alpine"
    # Set password (api gets pass from config json, see comment at the top of the file)
    command: redis-server --requirepass pass_for_development_purposes_only
    ports:
      - "6379:6379"
# I didn't specify connections/links because docker should take care of it by itself